[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "fittrix"
authors = [{name = "minarae", email = "minarae@fittrix.io"}]
dynamic = ["version", "description"]
